//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personregister.PersonServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchParameters", Namespace="http://register.nhn.no/PR")]
    [System.SerializableAttribute()]
    public partial class SearchParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipalityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchFhNumberPersonsTooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipalityCode {
            get {
                return this.MunicipalityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipalityCodeField, value) != true)) {
                    this.MunicipalityCodeField = value;
                    this.RaisePropertyChanged("MunicipalityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPlace {
            get {
                return this.PostalPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalPlaceField, value) != true)) {
                    this.PostalPlaceField = value;
                    this.RaisePropertyChanged("PostalPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage {
            get {
                return this.ResultsPerPageField;
            }
            set {
                if ((this.ResultsPerPageField.Equals(value) != true)) {
                    this.ResultsPerPageField = value;
                    this.RaisePropertyChanged("ResultsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchFhNumberPersonsToo {
            get {
                return this.SearchFhNumberPersonsTooField;
            }
            set {
                if ((this.SearchFhNumberPersonsTooField.Equals(value) != true)) {
                    this.SearchFhNumberPersonsTooField = value;
                    this.RaisePropertyChanged("SearchFhNumberPersonsToo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personregister.PersonServiceReference.Person[] PersonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personregister.PersonServiceReference.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personregister.PersonServiceReference.Person[] Persons {
            get {
                return this.PersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsField, value) != true)) {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personregister.PersonServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage {
            get {
                return this.ResultsPerPageField;
            }
            set {
                if ((this.ResultsPerPageField.Equals(value) != true)) {
                    this.ResultsPerPageField = value;
                    this.RaisePropertyChanged("ResultsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResults {
            get {
                return this.TotalResultsField;
            }
            set {
                if ((this.TotalResultsField.Equals(value) != true)) {
                    this.TotalResultsField = value;
                    this.RaisePropertyChanged("TotalResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://register.nhn.no/PR")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personregister.PersonServiceReference.Address[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCitizenshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCustodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateMaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateParentalResponsibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateWithoutLegalCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateWorkPermitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DufNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FathersNINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GivenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MothersNINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewNINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldNINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentalResponsibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseNINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WithoutLegalCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPermitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personregister.PersonServiceReference.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizenship {
            get {
                return this.CitizenshipField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipField, value) != true)) {
                    this.CitizenshipField = value;
                    this.RaisePropertyChanged("Citizenship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenshipCode {
            get {
                return this.CitizenshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipCodeField, value) != true)) {
                    this.CitizenshipCodeField = value;
                    this.RaisePropertyChanged("CitizenshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Custody {
            get {
                return this.CustodyField;
            }
            set {
                if ((object.ReferenceEquals(this.CustodyField, value) != true)) {
                    this.CustodyField = value;
                    this.RaisePropertyChanged("Custody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCitizenship {
            get {
                return this.DateCitizenshipField;
            }
            set {
                if ((this.DateCitizenshipField.Equals(value) != true)) {
                    this.DateCitizenshipField = value;
                    this.RaisePropertyChanged("DateCitizenship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCustody {
            get {
                return this.DateCustodyField;
            }
            set {
                if ((this.DateCustodyField.Equals(value) != true)) {
                    this.DateCustodyField = value;
                    this.RaisePropertyChanged("DateCustody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateMaritalStatus {
            get {
                return this.DateMaritalStatusField;
            }
            set {
                if ((this.DateMaritalStatusField.Equals(value) != true)) {
                    this.DateMaritalStatusField = value;
                    this.RaisePropertyChanged("DateMaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateParentalResponsibility {
            get {
                return this.DateParentalResponsibilityField;
            }
            set {
                if ((this.DateParentalResponsibilityField.Equals(value) != true)) {
                    this.DateParentalResponsibilityField = value;
                    this.RaisePropertyChanged("DateParentalResponsibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStatus {
            get {
                return this.DateStatusField;
            }
            set {
                if ((this.DateStatusField.Equals(value) != true)) {
                    this.DateStatusField = value;
                    this.RaisePropertyChanged("DateStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateWithoutLegalCapacity {
            get {
                return this.DateWithoutLegalCapacityField;
            }
            set {
                if ((this.DateWithoutLegalCapacityField.Equals(value) != true)) {
                    this.DateWithoutLegalCapacityField = value;
                    this.RaisePropertyChanged("DateWithoutLegalCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateWorkPermit {
            get {
                return this.DateWorkPermitField;
            }
            set {
                if ((this.DateWorkPermitField.Equals(value) != true)) {
                    this.DateWorkPermitField = value;
                    this.RaisePropertyChanged("DateWorkPermit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DufNo {
            get {
                return this.DufNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DufNoField, value) != true)) {
                    this.DufNoField = value;
                    this.RaisePropertyChanged("DufNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersNIN {
            get {
                return this.FathersNINField;
            }
            set {
                if ((object.ReferenceEquals(this.FathersNINField, value) != true)) {
                    this.FathersNINField = value;
                    this.RaisePropertyChanged("FathersNIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName {
            get {
                return this.GivenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GivenNameField, value) != true)) {
                    this.GivenNameField = value;
                    this.RaisePropertyChanged("GivenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((this.MaritalStatusField.Equals(value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersNIN {
            get {
                return this.MothersNINField;
            }
            set {
                if ((object.ReferenceEquals(this.MothersNINField, value) != true)) {
                    this.MothersNINField = value;
                    this.RaisePropertyChanged("MothersNIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN {
            get {
                return this.NINField;
            }
            set {
                if ((object.ReferenceEquals(this.NINField, value) != true)) {
                    this.NINField = value;
                    this.RaisePropertyChanged("NIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewNIN {
            get {
                return this.NewNINField;
            }
            set {
                if ((object.ReferenceEquals(this.NewNINField, value) != true)) {
                    this.NewNINField = value;
                    this.RaisePropertyChanged("NewNIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldNIN {
            get {
                return this.OldNINField;
            }
            set {
                if ((object.ReferenceEquals(this.OldNINField, value) != true)) {
                    this.OldNINField = value;
                    this.RaisePropertyChanged("OldNIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentalResponsibility {
            get {
                return this.ParentalResponsibilityField;
            }
            set {
                if ((this.ParentalResponsibilityField.Equals(value) != true)) {
                    this.ParentalResponsibilityField = value;
                    this.RaisePropertyChanged("ParentalResponsibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegStatus {
            get {
                return this.RegStatusField;
            }
            set {
                if ((this.RegStatusField.Equals(value) != true)) {
                    this.RegStatusField = value;
                    this.RaisePropertyChanged("RegStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sn {
            get {
                return this.SnField;
            }
            set {
                if ((object.ReferenceEquals(this.SnField, value) != true)) {
                    this.SnField = value;
                    this.RaisePropertyChanged("Sn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseNIN {
            get {
                return this.SpouseNINField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseNINField, value) != true)) {
                    this.SpouseNINField = value;
                    this.RaisePropertyChanged("SpouseNIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusCountryCode {
            get {
                return this.StatusCountryCodeField;
            }
            set {
                if ((this.StatusCountryCodeField.Equals(value) != true)) {
                    this.StatusCountryCodeField = value;
                    this.RaisePropertyChanged("StatusCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WithoutLegalCapacity {
            get {
                return this.WithoutLegalCapacityField;
            }
            set {
                if ((object.ReferenceEquals(this.WithoutLegalCapacityField, value) != true)) {
                    this.WithoutLegalCapacityField = value;
                    this.RaisePropertyChanged("WithoutLegalCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPermit {
            get {
                return this.WorkPermitField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPermitField, value) != true)) {
                    this.WorkPermitField = value;
                    this.RaisePropertyChanged("WorkPermit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://register.nhn.no/PR")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadastralNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstituencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CurrentAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateAdrFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatePostalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PostalAddressValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolDistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> XCoordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> YCoordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApartmentNumber {
            get {
                return this.ApartmentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentNumberField, value) != true)) {
                    this.ApartmentNumberField = value;
                    this.RaisePropertyChanged("ApartmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadastralNumber {
            get {
                return this.CadastralNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CadastralNumberField, value) != true)) {
                    this.CadastralNumberField = value;
                    this.RaisePropertyChanged("CadastralNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoAddress {
            get {
                return this.CoAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CoAddressField, value) != true)) {
                    this.CoAddressField = value;
                    this.RaisePropertyChanged("CoAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Constituency {
            get {
                return this.ConstituencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstituencyField, value) != true)) {
                    this.ConstituencyField = value;
                    this.RaisePropertyChanged("Constituency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CurrentAddress {
            get {
                return this.CurrentAddressField;
            }
            set {
                if ((this.CurrentAddressField.Equals(value) != true)) {
                    this.CurrentAddressField = value;
                    this.RaisePropertyChanged("CurrentAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAdrFrom {
            get {
                return this.DateAdrFromField;
            }
            set {
                if ((this.DateAdrFromField.Equals(value) != true)) {
                    this.DateAdrFromField = value;
                    this.RaisePropertyChanged("DateAdrFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatePostalType {
            get {
                return this.DatePostalTypeField;
            }
            set {
                if ((this.DatePostalTypeField.Equals(value) != true)) {
                    this.DatePostalTypeField = value;
                    this.RaisePropertyChanged("DatePostalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictCode {
            get {
                return this.DistrictCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictCodeField, value) != true)) {
                    this.DistrictCodeField = value;
                    this.RaisePropertyChanged("DistrictCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseLetter {
            get {
                return this.HouseLetterField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseLetterField, value) != true)) {
                    this.HouseLetterField = value;
                    this.RaisePropertyChanged("HouseLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HouseNumber {
            get {
                return this.HouseNumberField;
            }
            set {
                if ((this.HouseNumberField.Equals(value) != true)) {
                    this.HouseNumberField = value;
                    this.RaisePropertyChanged("HouseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipality {
            get {
                return this.MunicipalityField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipalityField, value) != true)) {
                    this.MunicipalityField = value;
                    this.RaisePropertyChanged("Municipality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressField, value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PostalAddressValidFrom {
            get {
                return this.PostalAddressValidFromField;
            }
            set {
                if ((this.PostalAddressValidFromField.Equals(value) != true)) {
                    this.PostalAddressValidFromField = value;
                    this.RaisePropertyChanged("PostalAddressValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPlace {
            get {
                return this.PostalPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalPlaceField, value) != true)) {
                    this.PostalPlaceField = value;
                    this.RaisePropertyChanged("PostalPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalType {
            get {
                return this.PostalTypeField;
            }
            set {
                if ((this.PostalTypeField.Equals(value) != true)) {
                    this.PostalTypeField = value;
                    this.RaisePropertyChanged("PostalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyNumber {
            get {
                return this.PropertyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNumberField, value) != true)) {
                    this.PropertyNumberField = value;
                    this.RaisePropertyChanged("PropertyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolDistrict {
            get {
                return this.SchoolDistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolDistrictField, value) != true)) {
                    this.SchoolDistrictField = value;
                    this.RaisePropertyChanged("SchoolDistrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string St {
            get {
                return this.StField;
            }
            set {
                if ((object.ReferenceEquals(this.StField, value) != true)) {
                    this.StField = value;
                    this.RaisePropertyChanged("St");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> XCoord {
            get {
                return this.XCoordField;
            }
            set {
                if ((this.XCoordField.Equals(value) != true)) {
                    this.XCoordField = value;
                    this.RaisePropertyChanged("XCoord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> YCoord {
            get {
                return this.YCoordField;
            }
            set {
                if ((this.YCoordField.Equals(value) != true)) {
                    this.YCoordField = value;
                    this.RaisePropertyChanged("YCoord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupParameters", Namespace="http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class LookupParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN {
            get {
                return this.NINField;
            }
            set {
                if ((object.ReferenceEquals(this.NINField, value) != true)) {
                    this.NINField = value;
                    this.RaisePropertyChanged("NIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityChange", Namespace="http://register.nhn.no/PR")]
    [System.SerializableAttribute()]
    public partial class IdentityChange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldNINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStatus {
            get {
                return this.DateStatusField;
            }
            set {
                if ((this.DateStatusField.Equals(value) != true)) {
                    this.DateStatusField = value;
                    this.RaisePropertyChanged("DateStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN {
            get {
                return this.NINField;
            }
            set {
                if ((object.ReferenceEquals(this.NINField, value) != true)) {
                    this.NINField = value;
                    this.RaisePropertyChanged("NIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldNIN {
            get {
                return this.OldNINField;
            }
            set {
                if ((object.ReferenceEquals(this.OldNINField, value) != true)) {
                    this.OldNINField = value;
                    this.RaisePropertyChanged("OldNIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://register.nhn.no/PR", ConfigurationName="PersonServiceReference.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/Search", ReplyAction="http://register.nhn.no/PR/IPersonService/SearchResponse")]
        Personregister.PersonServiceReference.SearchResult Search(Personregister.PersonServiceReference.SearchParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/Search", ReplyAction="http://register.nhn.no/PR/IPersonService/SearchResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.SearchResult> SearchAsync(Personregister.PersonServiceReference.SearchParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetPerson", ReplyAction="http://register.nhn.no/PR/IPersonService/GetPersonResponse")]
        Personregister.PersonServiceReference.Person GetPerson(Personregister.PersonServiceReference.LookupParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetPerson", ReplyAction="http://register.nhn.no/PR/IPersonService/GetPersonResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person> GetPersonAsync(Personregister.PersonServiceReference.LookupParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetPersons", ReplyAction="http://register.nhn.no/PR/IPersonService/GetPersonsResponse")]
        Personregister.PersonServiceReference.Person[] GetPersons(string[] listOfNIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetPersons", ReplyAction="http://register.nhn.no/PR/IPersonService/GetPersonsResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetPersonsAsync(string[] listOfNIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetAddresses", ReplyAction="http://register.nhn.no/PR/IPersonService/GetAddressesResponse")]
        Personregister.PersonServiceReference.Address[] GetAddresses(Personregister.PersonServiceReference.LookupParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetAddresses", ReplyAction="http://register.nhn.no/PR/IPersonService/GetAddressesResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.Address[]> GetAddressesAsync(Personregister.PersonServiceReference.LookupParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetChildren", ReplyAction="http://register.nhn.no/PR/IPersonService/GetChildrenResponse")]
        Personregister.PersonServiceReference.Person[] GetChildren(string NIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetChildren", ReplyAction="http://register.nhn.no/PR/IPersonService/GetChildrenResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetChildrenAsync(string NIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetIdentityChanges", ReplyAction="http://register.nhn.no/PR/IPersonService/GetIdentityChangesResponse")]
        Personregister.PersonServiceReference.IdentityChange[] GetIdentityChanges(System.DateTime from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetIdentityChanges", ReplyAction="http://register.nhn.no/PR/IPersonService/GetIdentityChangesResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.IdentityChange[]> GetIdentityChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetChanges", ReplyAction="http://register.nhn.no/PR/IPersonService/GetChangesResponse")]
        Personregister.PersonServiceReference.Person[] GetChanges(System.DateTime from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://register.nhn.no/PR/IPersonService/GetChanges", ReplyAction="http://register.nhn.no/PR/IPersonService/GetChangesResponse")]
        System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : Personregister.PersonServiceReference.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<Personregister.PersonServiceReference.IPersonService>, Personregister.PersonServiceReference.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Personregister.PersonServiceReference.SearchResult Search(Personregister.PersonServiceReference.SearchParameters parameters) {
            return base.Channel.Search(parameters);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.SearchResult> SearchAsync(Personregister.PersonServiceReference.SearchParameters parameters) {
            return base.Channel.SearchAsync(parameters);
        }
        
        public Personregister.PersonServiceReference.Person GetPerson(Personregister.PersonServiceReference.LookupParameters parameters) {
            return base.Channel.GetPerson(parameters);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person> GetPersonAsync(Personregister.PersonServiceReference.LookupParameters parameters) {
            return base.Channel.GetPersonAsync(parameters);
        }
        
        public Personregister.PersonServiceReference.Person[] GetPersons(string[] listOfNIN) {
            return base.Channel.GetPersons(listOfNIN);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetPersonsAsync(string[] listOfNIN) {
            return base.Channel.GetPersonsAsync(listOfNIN);
        }
        
        public Personregister.PersonServiceReference.Address[] GetAddresses(Personregister.PersonServiceReference.LookupParameters parameters) {
            return base.Channel.GetAddresses(parameters);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.Address[]> GetAddressesAsync(Personregister.PersonServiceReference.LookupParameters parameters) {
            return base.Channel.GetAddressesAsync(parameters);
        }
        
        public Personregister.PersonServiceReference.Person[] GetChildren(string NIN) {
            return base.Channel.GetChildren(NIN);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetChildrenAsync(string NIN) {
            return base.Channel.GetChildrenAsync(NIN);
        }
        
        public Personregister.PersonServiceReference.IdentityChange[] GetIdentityChanges(System.DateTime from, System.Nullable<System.DateTime> to) {
            return base.Channel.GetIdentityChanges(from, to);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.IdentityChange[]> GetIdentityChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to) {
            return base.Channel.GetIdentityChangesAsync(from, to);
        }
        
        public Personregister.PersonServiceReference.Person[] GetChanges(System.DateTime from, System.Nullable<System.DateTime> to) {
            return base.Channel.GetChanges(from, to);
        }
        
        public System.Threading.Tasks.Task<Personregister.PersonServiceReference.Person[]> GetChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to) {
            return base.Channel.GetChangesAsync(from, to);
        }
    }
}
